controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use PhpOffice\PhpWord\Shared\Converter;

use app\models\LoginForm;
use app\models\User;
use app\models\ContactForm;
use app\models\Pelayanan;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionSetRating($kode_pelacakan)
    {
        $model = Pelayanan::find()
            ->andWhere(['kode_pelacakan' => $kode_pelacakan])
            ->one();

        $rating = Yii::$app->request->post('rating');

        $model->rating = $rating;
        if($model->save(false)){
            Yii::$app->session->setFlash('success','Pelayanan Berhasil diberi rating !');
            return $this->redirect(Yii::$app->request->referrer);
        }        
    }

    public function actionSetKomentar($kode_pelacakan)
    {
        $model = Pelayanan::find()
            ->andWhere(['kode_pelacakan' => $kode_pelacakan])
            ->one();

        $komentar = Yii::$app->request->post('komentar');

        $model->komentar = $komentar;
        if($model->save(false)){
            Yii::$app->session->setFlash('success','Pelayanan Berhasil diberi komentar !');
            return $this->redirect(Yii::$app->request->referrer);
        }        
    }    

    /**
     * Displays homepage.
     *
     * @return string
     */

    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['admin/index']);
        } else{
            return $this->redirect(['site/login']);
        }
    }

    public function actionRegulasi()
    {
        $this->layout = 'frontend';
        return $this->render('regulasi');        
    }

    public function actionPengajuanPelayanan($id_pelayanan_jenis)
    {
        $this->layout = 'frontend';

        $model = new Pelayanan();

        $model->id_pelayanan_jenis = $id_pelayanan_jenis;

        if ($model->load(Yii::$app->request->post())) {
            $berkas_permohonan = UploadedFile::getInstance($model, 'berkas_permohonan');
            if ($berkas_permohonan !== null) {
                $model->berkas_permohonan = $berkas_permohonan->baseName . Yii::$app->formatter->asTimestamp(date('Y-d-m h:i:s')) . '.' . $berkas_permohonan->extension;
            }
            if ($model->save()) {
                //$model->sendMail();

                if ($berkas_permohonan!==null) {
                    $path = Yii::getAlias('@app').'/web/berkas/';
                    $berkas_permohonan->saveAs($path.$model->berkas_permohonan, false);
                }

                Yii::$app->session->setFlash('success','Pegajuan berhasil dikirim. Kode pelacakan Anda adalah <b>'.$model->kode_pelacakan.'</b> yang dapat digunakan untuk memeriksa status permohonan pelayanan Anda.');
                return $this->redirect(['site/index']);
            }
            Yii::$app->session->setFlash('error','Data gagal disimpan. Silahkan periksa kembali isian Anda.');

        }

        return $this->render('pengajuanPelayanan', [
            'model' => $model,
            'id_pelayanan_jenis' => $id_pelayanan_jenis
        ]);
    }

    public function actionGetBerkas($berkas)
    {        
        $path = Yii::getAlias('@web') . '/sop/'.$berkas;
        return $this->redirect($path);
    }

    public function actionTentang()
    {
        $this->layout = 'frontend';
        return $this->render('tentang');
    }

    public function actionPencarian($kode_pelacakan)
    {
        $this->layout = 'frontend';
        $model = Pelayanan::find()
            ->andWhere(['kode_pelacakan' => $kode_pelacakan])
            ->one();

        if ($model !==null){
            return $this->render('pencarian',['model' => $model]);
        } else{
            Yii::$app->session->setFlash('warning','Kode pelacakan tidak ditemukan !');
            return $this->redirect(['site/index']);
        }
    }

    public function actionLogin()
    {
        $this->layout = '/frontend/login';

        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['admin/index']);
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['admin/index']);
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }


}

views/site/_jenisLayanan.php
<section class="section-padding" id="about">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center wow fadeIn" data-wow-duration="500ms" data-wow-delay="300ms">
				<p class="title">Our Valued Services</p>
				<h2 class="heading">Ajukan Pelayanan Baru</h2>
			</div>
			<div class="col-md-4 col-sm-4 canvas-box magin30 text-center wow fadeInDown" data-wow-duration="500ms" data-wow-delay="300ms"> 
				<span class="text-center"><i class="icon-icons9 color6"></i></span>
				<h4 class="color6">Penggunaan Aula, R. Rapat, R. Kelas, R. Diskusi (Internal)</h4>
				<p>Keep away from people who try to belittle your ambitions. Small people always do that but the really great.</p>
			</div>
			<div class="col-md-4 col-sm-4 canvas-box magin30 text-center wow fadeInDown" data-wow-duration="500ms" data-wow-delay="500ms"> 
				<span class="text-center"><i class="icon-umbrella color1"></i></span>
				<h4 class="color1">Penggunaan Video Conference</h4>
				<p>Keep away from people who try to belittle your ambitions. Small people always do that but the really great.</p>
			</div>
			<div class="col-md-4 col-sm-4 canvas-box magin30 text-center wow fadeInDown" data-wow-duration="500ms" data-wow-delay="700ms"> 
				<span class="text-center"><i class="icon-icons20 color6"></i></span>
				<h4 class="color6">Perawatan Kendaraan Dinas Operasional</h4>
				<p>Keep away from people who try to belittle your ambitions. Small people always do that but the really great.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 col-sm-4 canvas-box magin30 text-center wow fadeInDown" data-wow-duration="500ms" data-wow-delay="900ms"> 
				<span class="text-center"><i class="icon-icons96  color1"></i></span>
				<h4 class="color1">Perbaikan/Perawatan Peralatan Kerja</h4>
				<p>Keep away from people who try to belittle your ambitions. Small people always do that but the really great.</p>
			</div>
			<div class="col-md-4 col-sm-4 canvas-box magin30 text-center wow fadeInDown" data-wow-duration="500ms" data-wow-delay="1100ms"> 
				<span class="text-center"><i class="icon-globe color6"></i></span>
				<h4 class="color6">Penggunaan Asrama (Internal)</h4>
				<p>Keep away from people who try to belittle your ambitions. Small people always do that but the really great.</p>
			</div>
			<div class="col-md-4 col-sm-4 canvas-box magin30 text-center wow fadeInDown" data-wow-duration="500ms" data-wow-delay="1200ms">
				<span class="text-center"><i class="icon-icons42 color1"></i></span>
				<h4 class="color1">Penggunaan Aula, R. Rapat, R. Kelas, R. Diskusi (Eksternal)</h4>
				<p>Keep away from people who try to belittle your ambitions. Small people always do that but the really great.</p>
			</div>
			<div class="col-md-4 col-sm-4 canvas-box magin30 text-center wow fadeInDown" data-wow-duration="500ms" data-wow-delay="1200ms">
				<span class="text-center"><i class="icon-icons42 color1"></i></span>
				<h4 class="color1">Penggunaan Asrama (Eksternal)</h4>
				<p>Keep away from people who try to belittle your ambitions. Small people always do that but the really great.</p>
			</div>      
		</div>
	</div>
</section>

views/site/_pelayananJenis.php
<?php
	use app\models\Pelayanan;
	use app\models\PelayananJenis;
	use yii\helpers\Url;
?>

<style type="text/css">
	.info-box {
		border: 1px solid #ccc;
		background-color: #efefef;
	}
</style>

<div class="row">
	<div class="col-md-4 col-sm-6 col-xs-12">
		<a href="<?= Url::to(['site/pengajuan-pelayanan','id_pelayanan_jenis' => PelayananJenis::AULA_INTERNAL]); ?>">
			<div class="info-box">
				<span class="info-box-icon bg-aqua"><i class="fa fa-building"></i></span>

				<div class="info-box-content">
					<span style="text-transform: uppercase; font-size: 16px; font-weight: bold" >Penggunaan Aula, R. Rapat, R. Kelas, R. Diskusi</span>
				</div>
				<!-- /.info-box-content -->
			</div>
		</a>
		<!-- /.info-box -->
	</div>
	<!-- /.col -->

	<?php /*
	<div class="col-md-4 col-sm-6 col-xs-12">
		<a href="<?= Url::to(['site/pengajuan-pelayanan','id_pelayanan_jenis' => PelayananJenis::AULA_EKSTERNAL]); ?>">
			<div class="info-box">
				<span class="info-box-icon bg-green"><i class="fa fa-building"></i></span>

				<div class="info-box-content">
					<span style="text-transform: uppercase; font-size: 16px; font-weight: bold" >Penggunaan Aula, R. Rapat, R. Kelas, R. Diskusi (Eksternal)</span>
				</div>			
			<!-- /.info-box-content -->
			</div>
		</a>
		<!-- /.info-box -->
	</div>	

	<?php */ ?>
	<!-- /.col -->

	<!-- /.col -->
	<div class="col-md-4 col-sm-6 col-xs-12">
		<a href="<?= Url::to(['site/pengajuan-pelayanan','id_pelayanan_jenis' => PelayananJenis::PERAWATAN_KENDARAAN]); ?>">
			<div class="info-box">
				<span class="info-box-icon bg-blue"><i class="fa fa-car"></i></span>

				<div class="info-box-content">
					<span style="text-transform: uppercase; font-size: 16px; font-weight: bold" >Perawatan Kendaraan Dinas Operasional</span>
				</div>			
				<!-- /.info-box-content -->
			</div>
		</a>
		<!-- /.info-box -->
	</div>
	<div class="col-md-4 col-sm-6 col-xs-12">
		<a href="<?= Url::to(['site/pengajuan-pelayanan','id_pelayanan_jenis' => PelayananJenis::ASRAMA_INTERNAL]); ?>">
			<div class="info-box">
				<span class="info-box-icon bg-aqua"><i class="fa fa-home"></i></span>

				<div class="info-box-content">
					<span style="text-transform: uppercase; font-size: 16px; font-weight: bold" >Penggunaan Asrama</span>
				</div>
				<!-- /.info-box-content -->
			</div>
		</a>
		<!-- /.info-box -->
	</div>
	<!-- /.col -->
	<?php /*
	<div class="col-md-4 col-sm-6 col-xs-12">
		<a href="<?= Url::to(['site/pengajuan-pelayanan','id_pelayanan_jenis' => PelayananJenis::ASRAMA_EKSTERNAL]); ?>">
			<div class="info-box">
				<span class="info-box-icon bg-green"><i class="fa fa-home"></i></span>

				<div class="info-box-content">
					<span style="text-transform: uppercase; font-size: 16px; font-weight: bold" >Penggunaan Asrama (Eksternal)</span>
				</div>			
				<!-- /.info-box-content -->
			</div>
		</a>
		<!-- /.info-box -->
	</div>

	<?php */ ?>

	<!-- /.col -->

	<div class="col-md-4 col-sm-6 col-xs-12">
		<a href="<?= Url::to(['site/pengajuan-pelayanan','id_pelayanan_jenis' => PelayananJenis::VIDEO_KONFERENSI]); ?>">
			<div class="info-box">
				<span class="info-box-icon bg-maroon"><i class="fa fa-users"></i></span>

				<div class="info-box-content">
					<span style="text-transform: uppercase; font-size: 16px; font-weight: bold" >Penggunaan Video Conference</span>
				</div>			
				<!-- /.info-box-content -->
			</div>
		</a>
		<!-- /.info-box -->
	</div>
	<!-- /.col -->
	<div class="col-md-4 col-sm-6 col-xs-12">
		<a href="<?= Url::to(['site/pengajuan-pelayanan','id_pelayanan_jenis' => PelayananJenis::PERALATAN_KERJA]); ?>">
			<div class="info-box">
				<span class="info-box-icon bg-red"><i class="fa fa-wrench"></i></span>

				<div class="info-box-content">
					<span style="text-transform: uppercase; font-size: 16px; font-weight: bold" >Perbaikan/Perawatan Peralatan Kerja</span>
				</div>			
				<!-- /.info-box-content -->
			</div>
		</a>
		<!-- /.info-box -->
	</div>

	<div class="col-md-4 col-sm-6 col-xs-12">
		<a href="<?= Url::to(['site/pengajuan-pelayanan','id_pelayanan_jenis' => PelayananJenis::PELAYANAN_LAIN_LAIN]); ?>">
			<div class="info-box">
				<span class="info-box-icon bg-orange"><i class="fa fa-outdent"></i></span>

				<div class="info-box-content">
					<span style="text-transform: uppercase; font-size: 16px; font-weight: bold" >Pelayanan Umum / Lain-Lain</span>
				</div>			
				<!-- /.info-box-content -->
			</div>
		</a>
		<!-- /.info-box -->
	</div>	
</div>

views/site/_slideshow.php
<?php

use yii\helpers\Url;

?>

<section>
  
  <div class="tp-banner-container">
    <div class="fullscreenbanner tp-banner">      
      <ul>	<!-- SLIDE  -->
        <li data-transition="fade" data-slotamount="6" data-delay="5000">
        <!-- MAIN IMAGE -->
       	 <img  src="images/slide1.jpg" alt="slidebg1" data-bgfit="cover" data-bgposition="center center">
        
           <!-- LAYER NR. 1 -->
           <p class="tp-caption sft tp-resizeme"
           data-x="center"
           data-y="150" 
           data-speed="500"
           data-start="1000"
           data-easing="Power3.easeInOut"
           data-elementdelay="0.1"
           data-endelementdelay="0.1"
           style="z-index: 5;">SIPEKA
           </p>
        <!-- LAYER NR. 2 -->
           <h2 class="tp-caption sft tp-resizeme text-center"
           data-x="center"
           data-y="190" 
           data-speed="500"
           data-start="1500"
           data-easing="Power3.easeInOut"
           data-elementdelay="0.05"
           data-endelementdelay="0.1"
           style="z-index: 9;">
           SIPEKA<br>LAN JAKARTA
           </h2>
            <!-- LAYER NR. 3 --> 
           <p class="tp-caption sft tp-resizeme"
           data-x="center"
           data-y="330" 
           data-speed="500"
           data-start="2000"
           data-easing="Power3.easeInOut"
           data-elementdelay="0.1"
           data-endelementdelay="0.1"
           style="z-index: 5;">Sistem Permohonan dan Monitoring Layanan LAN JAKARTA
           </p>
           
           
        <!-- LAYER NR. 4 -->
           <div class="tp-caption sft tp-resizeme"
           data-x="center"
           data-y="440" 
           data-speed="500"
           data-start="2500"
           data-easing="Power3.easeInOut"
           data-elementdelay="0.1"
           data-endelementdelay="0.1"
           data-linktoslide="next"
           style="z-index: 12;">
           <a href="<?= Url::to(['site/login']); ?>" class="btn btn-flat btn-app btn-blue bounce-white" style="border-radius:0px !important">Login Aplikasi SIPEKA</a>
           </div>
        
        </li>
      </ul>
    </div>
  </div>
</section>

views/site/_statistik.php
<?php

use yii\helpers\Html; 

?>

<div style="position:relative;">
	<section id="bg-paralax">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 text-center">
					<?= Html::img('images/logo-besar.png',null,array('class'=>'img-responsive')); ?>
				</div>

				<div class="col-md-6 text-left">
					<h2 class="magin30">Statistik Pengguna E-Learning</h2>
					<p>Aplikasi e-elarning sudah digunakan di lingkungan STIA LAN Jakarta per tahun 2017. Berikut ini statistik penggunanya</p>
					<div class="row">
						<div class="col-sm-3">
							<div style="font-size: 50px"><i class="fa fa-sitemap"></i></div>
							<h1>4</h1>
							<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod</div>
						</div>
						<div class="col-sm-3">
							<div style="font-size: 50px"><i class="fa fa-briefcase"></i></div>
							<h1>5</h1>
							<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod</div>
						</div>
						<div class="col-sm-3">
							<div style="font-size: 50px"><i class="fa fa-edit"></i></div>
							<h1>7</h1>
							<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod</div>
						</div>
						<div class="col-sm-3">
							<div style="font-size: 50px"><i class="fa fa-bar-chart"></i></div>
							<h1>12</h1>
							<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod</div>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</section>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/pencarian.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\PelayananStatus;
use app\models\PelayananJenisTahapan;
use app\components\Helper;


$this->title = "Pengajuan Pelayanan Dengan Kode Pelacakan : ". $model->kode_pelacakan;
?>


<div class="pelayanan-view box box-info">
    <div class="box-header">
        <h3 class="box-title"><i class="fa fa-comment-o"></i> Detail Pelayanan : <b><?= $model->kode_pelacakan; ?></b></h3>
    </div>

    <div class="box-body">

    <?= DetailView::widget([
        'model' => $model,
        'template' => '<tr><th width="180px" style="text-align:right">{label}</th><td>{value}</td></tr>',
        'attributes' => [
            [
                'attribute' => 'id_pelayanan_jenis',
                'format' => 'raw',
                'value' => $model->pelayananJenis->nama,
            ],
            [
                'attribute' => 'id_pelayanan_status',
                'format' => 'raw',
                'value' => '<label class="'.$model->getClassLabel().'" style="font-size: 13px">'.$model->pelayananStatus->nama.'</label>',
            ],
            [
                'attribute' => 'kode_pelacakan',
                'format' => 'raw',
                'value' => $model->kode_pelacakan,
            ],
        ],
    ]) ?>
    </div>
</div>

<?php if($model->id_pelayanan_status == PelayananStatus::SELESAI){ ?>

<?= Html::beginForm(['site/set-rating', 'kode_pelacakan' => $model->kode_pelacakan], 'post') ?>
    <div class="pelayanan-view box box-warning">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-star-o"></i> Rating Pelayanan</h3>
        </div>

        <div class="box-body">
            <?= $model->getRating(); ?>
        </div>

        <?php if(!$model->isTelahDirating()){ ?>
        <div class="box-footer with-border">
            <?= Html::submitButton('<i class="fa fa-check"></i> Beri Rating', ['encodeLabels' => true, 'class' => 'btn btn-success btn-flat']) ?>
        </div>
        <?php } ?>    
    </div>
<?= Html::endForm() ?>

<?= Html::beginForm(['site/set-komentar', 'kode_pelacakan' => $model->kode_pelacakan], 'post') ?>
    <div class="pelayanan-view box box-info">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-comments-o"></i> Komentar</h3>
        </div>

        <div class="box-body">
            <div class="row">
                <div class="col-sm-7">
                    <?= $model->getKomentar(); ?>
                </div>
            </div>
        </div>

        <?php if(!$model->isTelahDikomentar()){ ?>
        <div class="box-footer with-border">
            <?= Html::submitButton('<i class="fa fa-check"></i> Tambah Komentar', ['encodeLabels' => true, 'class' => 'btn btn-success btn-flat']) ?>
        </div>
        <?php } ?>

    </div>
<?= Html::endForm() ?>

<?php } ?>


<div class="pelayanan-view box box-info">
    <div class="box-header">
        <h3 class="box-title"><i class="fa fa-user-o"></i> Detail Pemohon</h3>
    </div>
    <div class="box-body">

    <?= DetailView::widget([
        'model' => $model,
        'template' => '<tr><th width="180px" style="text-align:right">{label}</th><td>{value}</td></tr>',
        'attributes' => [
            [
                'attribute' => 'nama_pemohon',
                'format' => 'raw',
                'value' => $model->nama_pemohon,
            ],
            [
                'attribute' => 'unit_kerja_pemohon',
                'format' => 'raw',
                'value' => $model->unit_kerja_pemohon,
            ],
            [
                'attribute' => 'instansi_pemohon',
                'format' => 'raw',
                'value' => $model->instansi_pemohon,
            ],
            [
                'attribute' => 'alamat_pemohon',
                'format' => 'raw',
                'value' => $model->alamat_pemohon,
            ],
            [
                'attribute' => 'telepon_pemohon',
                'format' => 'raw',
                'value' => $model->telepon_pemohon,
            ],
            [
                'attribute' => 'email_pemohon',
                'format' => 'raw',
                'value' => $model->email_pemohon,
            ],
        ],
    ]) ?>
    </div>
</div>
<div class="pelayanan-view box box-info">
    <div class="box-header">
        <h3 class="box-title"><i class="fa fa-list"></i> Detail Permohonan</h3>
    </div>
    <div class="box-body">

    <?= DetailView::widget([
        'model' => $model,
        'template' => '<tr><th width="180px" style="text-align:right">{label}</th><td>{value}</td></tr>',
        'attributes' => [
            [
                'attribute' => 'berkas_permohonan',
                'format' => 'raw',
                'value' => Html::a("<i class='fa fa-download'></i> Unduh Berkas disini",['pelayanan/get-berkas','id'=>$model->id],['class' => 'btn btn-success btn-flat']),
            ],
            [
                'attribute' => 'tanggal_permohonan',
                'format' => 'raw',
                'value' => Helper::getTanggal($model->tanggal_permohonan),
            ],
            [
                'attribute' => 'tanggal_mulai_proses',
                'format' => 'raw',
                'value' => Helper::getTanggal($model->tanggal_mulai_proses),
            ],
            [
                'attribute' => 'tanggal_selesai_proses',
                'format' => 'raw',
                'value' => Helper::getTanggal($model->tanggal_selesai_proses),
            ],
            [
                'attribute' => 'keterangan',
                'format' => 'raw',
                'value' => $model->keterangan,
            ],
        ],
    ]) ?>

    </div>
</div>

<?php if ($model->id_pelayanan_status == PelayananStatus::DITOLAK): ?>
    <div class="alert alert-warning"><i class="fa fa-warning"></i> Pelayanan Ini telah ditolak !</div>

    <div class="box box-danger">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-warning"></i> Alasan Ditolak</h3>
        </div>
        <div class="box-body">
            <?= $model->alasan_ditolak; ?>
        </div>
    </div>
<?php endif ?>

<div class="row">
    <div class="col-sm-offset-1 col-sm-10">

        <ul class="timeline">

            <!-- timeline time label -->
            <li class="time-label">
                <span class="bg-maroon">
                    <i class="fa fa-random"></i> Runtunan Tahapan Pelayanan
                </span>
            </li>
            <!-- /.timeline-label -->

                <?php foreach ($model->pelayananJenisTahapans as $data): ?>
                <li>
                    <!-- timeline icon -->
                    <i data-widget="collapse" data-placement="left" data-toggle="tooltip" title="<?= $data->getTitleSelesai($model->id); ?>" class="fa bg-blue" style="font-weight: bold "><?= $data->urutan; ?></i>
                    <?= $data->getChecklist($model->id); ?>


                    <div data-widget="collapse" data-toggle="tooltip" data-placement="right" title="<?= $data->getTitleSelesai($model->id); ?>" class="timeline-item <?= $data->getBgSelesai($model->id); ?> ">
                        <span class="time" <?= $data->getColorSelesai($model->id); ?>><i class="fa fa-clock-o"></i> <?= $data->waktu; ?></span>

                        <h3 class="timeline-header"><a <?= $data->getColorSelesai($model->id); ?> >Tahapan <?= $data->urutan; ?></a></h3>

                        <div class="timeline-body">
                            <?= $data->kegiatan; ?>
                        </div>
                    </div>
                </li>

                <?php endforeach ?>
        </ul>
    </div>
</div>

views/site/tes.php
Lorem ipsum dolor sit amet, consectetur adipisicing elit. In sed quibusdam, omnis et nisi voluptas. Vero veritatis, officia consequatur provident. Consequuntur debitis vero at itaque, similique numquam quos, sint facilis, ab ad vel earum voluptas unde excepturi minus, consectetur possimus est ipsam? Odit vitae sed, saepe non iste ratione voluptas placeat delectus, quos neque laborum modi ducimus? Ea incidunt totam asperiores praesentium expedita quis alias, voluptates ratione nulla enim, a, voluptatem provident aut culpa quia! Quasi animi odit quaerat aspernatur maxime placeat vitae. Dolorem laborum consectetur similique, culpa natus magni eos deserunt! Similique nulla, quam reiciendis! Perspiciatis molestias dicta unde.